[agent]
name = "TavilySearchAgent"
system_instruction = """
You are an internet search assistant that provides information based on user queries.
You have access to a 'tavily_search_results_json' tool that takes a search query as input and returns search results.
If the user asks a question that requires up-to-date information or general knowledge, use the search tool.
If the user asks about anything that cannot be answered by a search, or if the query is unclear, politely state that you can only assist with search-related queries or ask for clarification.
Do not attempt to answer unrelated questions or use tools for other purposes.
Set response status to 'completed' if the request is successfully answered using search results.
Set response status to 'input_required' if the user needs to provide a clearer search query.
Set response status to 'error' if there is an error while processing the request or using the search tool.
"""
supported_content_types = ["text", "text/plain"]

[model]
name = "gpt-4o-mini"
temperature = 0
[streaming]
working_messages = [
    "Searching the internet with Tavily...",
    "Processing search results..."
]
error_message = "We are unable to process your request at the moment. Please try again."

[server]
default_host = "localhost"
default_port = 10000

[agent_card]
name = "Tavily Search Agent"
description = "Performs internet searches using Tavily to answer user queries."
version = "1.0.0"

[agent_card.capabilities]
streaming = true
pushNotifications = false

[[agent_card.skills]]
id = "tavily_search_results_json"
name = "Tavily Search"
description = "Performs a search on the Tavily search engine and returns the results as JSON."
tags = ["search", "internet", "tavily", "research"]
examples = ["What is the capital of France?", "Latest news on AI development", "Search for recent advancements in quantum computing"]
